#!/usr/bin/env sh

# bin/skript bootstrap: Prints the source of `bootstrap` script.

set -o errexit   # Always exit on error
set -o nounset   # Treat unset variables as errors

read -d="" tmpl << EOF || true
#!/usr/bin/env sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -o errexit   # Always exit on error
set -o nounset   # Treat unset variables as errors
set -o xtrace    # Print a trace of simple commands

EOF

mkdir -p script

echo "$tmpl" > script/bootstrap
chmod +x script/bootstrap
