#!/usr/bin/env sh

# bin/skript help: Prints usage instructions.

set -o errexit   # Always exit on error
set -o nounset   # Treat unset variables as errors

read -d="" message << EOF || true
Usage: skript <command>

Commands:

    init <name>     Bootstraps a script in 'script' directory. Following scripts
                    are supported: setup, bootstrap, test, update.

                    Example:

                        skript init setup

                    See https://github.com/github/scripts-to-rule-them-all#scriptsetup
    help            Prints this message.
EOF

echo "$message"
