#!/usr/bin/env sh

# bin/skript setup: Prints the source of `setup` script.

set -o errexit   # Always exit on error
set -o nounset   # Treat unset variables as errors

read -d="" tmpl << EOF || true
#!/usr/bin/env sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -o errexit   # Always exit on error
set -o nounset   # Treat unset variables as errors
set -o xtrace    # Print a trace of simple commands

script/bootstrap
EOF

echo "$tmpl"
